FROM golang:1.19.2-bullseye

RUN mkdir /app && mkdir /app/src
WORKDIR /app/src

ENV GOPATH /go

RUN apt-get update \
    && apt-get install -y git vim

RUN apt-get install -y tzdata && \
    ln -sf /usr/share/zoneinfo/Asia/Tokyo /etc/localtime
    
RUN go install golang.org/x/tools/gopls@latest
RUN go install github.com/ramya-rao-a/go-outline@latest
RUN go install github.com/go-delve/delve/cmd/dlv@latest

RUN go install github.com/cosmtrek/air@latest
RUN go install honnef.co/go/tools/cmd/staticcheck@latest